### ISSUE TITLE
Je n'arrive pas à envoyer un nouveau firmware

### ISSUE THREAD

**Issue by Leobriand31** [garatronic/nadhat_pyb#3]
Voici le log : 
sudo make deployUse make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
GEN build-PYBV10/genhdr/mpversion.h
CC ../../lib/utils/pyexec.c
CC moduos.c
LINK build-PYBV10/firmware.elf
   text	   data	    bss	    dec	    hex	filename
 336160	     32	  27844	 364036	  58e04	build-PYBV10/firmware.elf
GEN build-PYBV10/firmware.dfu
Writing build-PYBV10/firmware.dfu to the board
Traceback (most recent call last):
  File "../../tools/pydfu.py", line 21, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'
Makefile:504: recipe for target 'deploy' failed
make: *** [deploy] Error 1

**Comment by garatronic** [comment]
Bonjour Léo,

Tu peux essayer de réinitiliser la carte et reformater le filesystem du micro avec la séquence de bouton RESET/USER. C'est décrit dans la doc micropython là : https://docs.micropython.org/en/latest/pyboard/tutorial/reset.html

**Comment by garatronic** [comment]
Cela ne corrige en rien les difficultés que tu as à télécharger le firmware. Je te propose de suivre ça sur le forum.garatronic.fr
